// @generated
// This file is generated by scripts/generate-sidecar-event-types.mjs from resources/sidecar_events.json.

/**
 * Sidecar event envelope emitted over stdout.
 */

export interface LspPortEvent {
    event: 'lsp_port';
    port: number;
}

export interface ErrorEvent {
    event: 'error';
    message: string;
}

export interface KernelStatusEvent {
    event: 'kernel_status';
    status: 'idle' | 'busy' | 'starting' | 'unknown';
}

export interface AliveEvent {
    event: 'alive';
}

export interface CommOpenEvent {
    event: 'comm_open';
    comm_id: string;
    target_name: string;
    data: Record<string, unknown>;
}

export interface UiCommOpenEvent {
    event: 'ui_comm_open';
    comm_id: string;
    target_name: string;
    data?: Record<string, unknown>;
}

export interface HelpCommOpenEvent {
    event: 'help_comm_open';
    comm_id: string;
    target_name: string;
    data?: Record<string, unknown>;
}

export interface VariablesCommOpenEvent {
    event: 'variables_comm_open';
    comm_id: string;
    target_name: string;
    data?: Record<string, unknown>;
}

export interface DataExplorerCommOpenEvent {
    event: 'data_explorer_comm_open';
    comm_id: string;
    target_name: string;
    data?: Record<string, unknown>;
}

export interface CommMsgEvent {
    event: 'comm_msg';
    comm_id: string;
    data: Record<string, unknown>;
}

export interface CommCloseEvent {
    event: 'comm_close';
    comm_id: string;
}

export interface ShowHtmlFileEvent {
    event: 'show_html_file';
    comm_id: string;
    data: Record<string, unknown>;
}

export interface ShowHelpEvent {
    event: 'show_help';
    comm_id: string;
    data: Record<string, unknown>;
}

export interface DisplayDataEvent {
    event: 'display_data';
    data: string;
    display_id?: string | null;
}

export interface UpdateDisplayDataEvent {
    event: 'update_display_data';
    data: string;
    display_id?: string | null;
}

export type SidecarEvent = LspPortEvent | ErrorEvent | KernelStatusEvent | AliveEvent | CommOpenEvent | UiCommOpenEvent | HelpCommOpenEvent | VariablesCommOpenEvent | DataExplorerCommOpenEvent | CommMsgEvent | CommCloseEvent | ShowHtmlFileEvent | ShowHelpEvent | DisplayDataEvent | UpdateDisplayDataEvent;
